### ISSUE TITLE
Bot doesn't publish every sixth message

### ISSUE THREAD

**Issue by Incoming5643** [Vedinsoh/discord-auto-publisher#26]
Bot will publish five messages fine, then skip the sixth. The cycle then repeats.

Using this with a webhook bot that posts twice an hour (every thirty minutes). So it misses a message once every three hours.

**Comment by Incoming5643** [comment]
Pattern has ended, now missing messages in no clear patterns. Published fine through the night 12:50 AM to 7:50 AM EST. Missed 8:20 AM and 9:20 AM. Might be due to load at certain times?

**Comment by Vedinsoh** [comment]
I've noticed the issue as well, gonna deploy the fix when I identify the cuase

**Comment by Vedinsoh** [comment]
I've reworked the way messages are published, let me know if the issues persist.
