### ISSUE TITLE
Queuing system

### ISSUE THREAD

**Issue by eliahilse** [Vedinsoh/discord-auto-publisher#36]
Would be awesome if the bot could just queue announcements over the rate limit & send out as the rate limit allows.
Sometimes, in the heat of the battle 10 edits to an announcement can happen, and it'd be cool if anything above that doesn't get lost, but just sent out delayed.

Regarding this:
![grafik](https://github.com/Vedinsoh/discord-auto-publisher/assets/83713217/aaa2d5eb-8303-4549-a28b-02694c6b0872)
How about doing internal ratelimiting management?
I suppose the reason for this is that you don't want to get blacklisted by discord for hitting the limits too often, therefore it might make more sense to just have the ratelimiting be done internally - and then periodically automatically test if discord has increased the ratelimits.

**Comment by Vedinsoh** [comment]
The bot already has an internal queueing mechanism, in fact it has the following measures to help avoid hitting the rate limits repeatedly (in the following order):
- Per-channel rolling counter - determines if the channel has reached 10 messages or not (prevents sending an extra request if it did)
- Per-channel queue - prevent a single channel from flooding the queues
- Per-client queue - prevents hitting the rate limit for `/crosspost` route
